#!/usr/bin/env python3
#
# Copyright 2026 Free Software Foundation, Inc.
#
# This file is part of VOLK
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
"""Black-box regression test for volk_profile's volk_config round-trip.

Drives the built ``volk_profile`` binary in update mode (``-u``) against a
pre-seeded single-kernel config and asserts that the aligned/unaligned
best-arch columns survive a read -> write round-trip unchanged, and that a
second pass is byte-identical (idempotent).

The canonical on-disk column order (matching ``write_results`` and the
library's ``lib/volk_prefs.c`` reader) is:

    <kernel_name>  <best_arch_a (aligned)>  <best_arch_u (unaligned)>

This test fails if ``read_results`` transposes the aligned/unaligned fields
(the defect fixed by mtibbits/volk#158): on the buggy code a single ``-u``
pass rewrites the kernel line with the two arch columns swapped.

The kernel ``volk_32f_x2_add_32f`` is used because its name is not a
substring of any other registered kernel, so ``-R`` matches exactly one
test case and -- since that kernel is already present in the seeded config --
no kernel is actually profiled (the run is fast and deterministic). The arch
tokens are opaque to read/write_results; only their distinctness matters.
"""

import argparse
import os
import subprocess  # nosec B404 - drives the locally-built volk_profile binary
import sys
import tempfile

KERNEL = "volk_32f_x2_add_32f"
ARCH_A = "a_avx"  # aligned   -> column 1
ARCH_U = "u_sse"  # unaligned -> column 2


def kernel_lines(text):
    """Return the 3-token (name arch_a arch_u) lines, skipping comments/blanks."""
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) == 3:
            rows.append(parts)
    return rows


def run_update(binary, cfgdir):
    proc = subprocess.run(  # nosec B603 - fixed argv, no shell, test-controlled inputs
        [binary, "-u", "-p", cfgdir, "-R", KERNEL],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        universal_newlines=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout or "")
        raise SystemExit(
            "volk_profile -u exited %d (see output above)" % proc.returncode
        )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--binary", required=True, help="path to the volk_profile binary")
    args = ap.parse_args()

    with tempfile.TemporaryDirectory(prefix="volk_cfg_rt_") as tmp:
        cfg = os.path.join(tmp, "volk_config")
        # Seed a config with a single kernel and DISTINCT aligned/unaligned arches.
        with open(cfg, "w") as f:
            f.write("#this file is generated by volk_profile.\n")
            f.write("#the function name is followed by the preferred architecture.\n")
            f.write("%s %s %s\n" % (KERNEL, ARCH_A, ARCH_U))

        # First -u pass: read the seed, skip (already present), write it back.
        run_update(args.binary, tmp)
        with open(cfg) as f:
            out1 = f.read()
        rows1 = kernel_lines(out1)

        # Exactly one kernel line proves nothing else was profiled.
        if len(rows1) != 1:
            sys.stderr.write(
                "FAIL: expected exactly 1 kernel line after -u, got %d:\n%s\n"
                % (len(rows1), out1)
            )
            return 1

        name, arch_a, arch_u = rows1[0]
        if name != KERNEL or arch_a != ARCH_A or arch_u != ARCH_U:
            sys.stderr.write(
                "FAIL: aligned/unaligned columns not preserved across the "
                "read->write round-trip.\n"
                "  expected: %s %s %s\n"
                "  got:      %s %s %s\n"
                "  (transposed columns => read_results swaps best_arch_a/"
                "best_arch_u)\n" % (KERNEL, ARCH_A, ARCH_U, name, arch_a, arch_u)
            )
            return 1

        # Second -u pass must reproduce the file byte-for-byte (idempotent).
        run_update(args.binary, tmp)
        with open(cfg) as f:
            out2 = f.read()
        if out2 != out1:
            sys.stderr.write(
                "FAIL: second -u pass is not byte-identical (non-idempotent).\n"
                "--- pass 1 ---\n%s\n--- pass 2 ---\n%s\n" % (out1, out2)
            )
            return 1

    sys.stdout.write("PASS: a/u columns preserved; -u round-trip is idempotent.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
